// LOCALHOST REQUESTS

### get all contacts info
GET http://localhost:3000/contacts

### get Brandy's info
GET http://localhost:3000/contacts/650ba03e85570f2b30ac52e9

### get Jeff's info
GET http://localhost:3000/contacts/650ba0d185570f2b30ac52ea

### get Emmri's info
GET http://localhost:3000/contacts/650ba0e285570f2b30ac52eb

### get recently created contact's info - MUST REPLACE ID!!!
GET http://localhost:3000/contacts/650ba0e285570f2b30ac52eb

### Create new contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
  "firstName": "Annelise",
  "lastName": "Stinson",
  "birthday": "Septeber 2",
  "email": "astinson@email.com",
  "favoriteColor": "blue"  
}

### Update existing contact - MUST REPLACE ID!!!
PUT http://localhost:3000/contacts/650ba0d185570f2b30ac52ea HTTP/1.1
content-type: application/json

{
  "firstName": "Tauren",
  "lastName": "Stinson",
  "birthday": "May 25",
  "email": "tstinson@email.com",
  "favoriteColor": "green"  
}

### Delete contact by ID - MUST REPLACE ID!!!
DELETE http://localhost:3000/contacts/6516d9acfc426d06c536a77d

// RENDER REQUESTS

### get all contacts info on Render
GET https://cse341-afb3.onrender.com/contacts

### get Brandy's info on Render
GET https://cse341-afb3.onrender.com/contacts/650ba03e85570f2b30ac52e9

### get Jeff's info on Render
GET https://cse341-afb3.onrender.com/contacts/650ba0d185570f2b30ac52ea

### get Emmri's info on Render
GET https://cse341-afb3.onrender.com/contacts/650ba0e285570f2b30ac52eb

### get resently created contact's info on Render - MUST REPLACE ID!!!
GET https://cse341-afb3.onrender.com/contacts/6516e0d471be9aaadadc3570

### Create new contact
POST https://cse341-afb3.onrender.com/contacts HTTP/1.1
content-type: application/json

{
  "firstName": "Annelise",
  "lastName": "Stinson",
  "birthday": "Septeber 2",
  "email": "astinson@email.com",
  "favoriteColor": "blue"  
}

### Update existing contact - MUST REPLACE ID!!!
PUT https://cse341-afb3.onrender.com/contacts/6516e0d471be9aaadadc3570 HTTP/1.1
content-type: application/json

{
  "firstName": "Tauren",
  "lastName": "Stinson",
  "birthday": "May 25",
  "email": "tstinson@email.com",
  "favoriteColor": "green"  
}

### Delete contact by ID - MUST REPLACE ID!!!
DELETE https://cse341-afb3.onrender.com/contacts/6516e12171be9aaadadc3571
